### ISSUE TITLE
MudSlider wrong value

### ISSUE THREAD

**Issue by anasseb** [fullstackhero/blazor-wasm-boilerplate#161]
Hello,

In the product page, the MaximumRate is set to 9999, when moving left the slider one step, the value is 99.

**Comment by MikaelHild** [comment]
Hi,
Maybe the mudslider is not the best option for determining a range for the rates. 
However, it can be fixed by adding Min & Max attributes to the Mudslider. Consider also a step attribute.

` <MudSlider T="decimal" @bind-value="SearchMaximumRate" Min="0" Max="9999" Step="100">@L["Maximum Rate"]: @_searchMaximumRate.ToString()</MudSlider>`

**Comment by anasseb** [comment]
> Hi, Maybe the mudslider is not the best option for determining a range for the rates. However, it can be fixed by adding Min & Max attributes to the Mudslider. Consider also a step attribute.
> 
> ` <MudSlider T="decimal" @bind-value="SearchMaximumRate" Min="0" Max="9999" Step="100">@L["Maximum Rate"]: @_searchMaximumRate.ToString()</MudSlider>`

Thanks, I'll test it.
